### ISSUE TITLE
its not an issues.

### ISSUE THREAD

**Issue by comeonline** [jacobedawson/connect-metamask-react-dapp#1]
Is it possible to show the actual crypto name instead of ETH. If wallet connected with BSC, show BNB and so on.

On Account Modal, its opening ropsten link. Is it possible to open the actual explorer link from which network metamask connected.

**Comment by volkstoken** [comment]
That's something I would like also. And was wondering if there is a way to get assets from the connected MetaMask.

**Comment by jacobedawson** [comment]
Yep you can do that easily in useDapp: https://usedapp.readthedocs.io/en/latest/getting-started.html#token-balance

```
import { formatUnits } from '@ethersproject/units'

const DAI = '0x6b175474e89094c44da98b954eedeac495271d0f';

export function TokenBalance() {
  const { account } = useEthers();
  const tokenBalance = useTokenBalance(DAI, account);

  return (
    <div>
      {tokenBalance && <p>Balance: {formatUnits(tokenBalance, 18)}</p>}
    </div>
  )
}
```

**Comment by jacobedawson** [comment]
> Is it possible to show the actual crypto name instead of ETH. If wallet connected with BSC, show BNB and so on.
> 
> On Account Modal, its opening ropsten link. Is it possible to open the actual explorer link from which network metamask connected.

Yes in terms of this you can get the chainId and use that to query e.g. an object to pull the appropriate etherscan (or other explorer link)

**Comment by volkstoken** [comment]
Thank you for your reply. Sorry for not starting a new issue.

**Comment by jacobedawson** [comment]
> Thank you for your reply. Sorry for not starting a new issue.

No worries at all :)
